name: Read GSheet (manual or monthly)

on:
  workflow_dispatch:  # bisa dijalankan manual
  schedule:
    - cron: '50 16 28-31 * *'  # 23:50 WIB = 16:50 UTC

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node index.js
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
