name: GSheet to Supabase

on:
  schedule:
    - cron: '0 * * * *'  # Setiap jam UTC (WIB +7 berarti jam 7 pagi = jam 00 UTC)
  workflow_dispatch:

jobs:
  sync-gsheet-supabase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Log current time (UTC & WIB)
        run: |
          echo "🕓 UTC: $(date -u)"
          echo "🌏 WIB: $(TZ=Asia/Jakarta date)"

      - name: Run sync script
        run: node index.js
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
